import {
  GrammarGeneratorConfig,
  GrammarPlugin,
  GeneratedGrammar,
  PluginGrammarConfig,
  TokenDefinition,
} from "../types.js";
import { validateConfig } from "./validation.js";
import {
  generateTokensSection,
  generateRulesSection,
  generatePrecedenceSection,
  generateMacrosSection,
} from "./sections.js";
import { getStartRule, getCommentToken } from "./utils.js";
import { mergePlugins, orderPlugins, rulesToAstTypes } from "./plugins.js";

export function generateGrammar(
  config: GrammarGeneratorConfig,
): GeneratedGrammar {
  const tokens = config.tokens || [];
  const errors = validateConfig(config);
  const imports: string[] = [];

  // Build tokens section
  const tokensSection = generateTokensSection(tokens);

  // Build rules section
  const rulesSection = generateRulesSection(config);

  // Build top rule
  const topRule = `@top ${config.grammarName} { ${getStartRule(config)} }`;

  // Build skip section
  const skipSection =
    config.skipWhitespace !== false
      ? `@skip { whitespace | ${getCommentToken(tokens)} }`
      : "";

  // Build precedence section if needed
  const precedenceSection = generatePrecedenceSection(config);

  // Build macros section
  const macrosSection = generateMacrosSection(config.macros);

  const grammar = `/**
 * Generated by @fossiq/lezer-grammar-generator
 * Generated from AST type definitions
 */
${topRule}

${rulesSection}

@tokens {
${tokensSection}
${precedenceSection}}

${skipSection}

${macrosSection}
`;

  return {
    grammar,
    imports,
    errors,
  };
}

export function generateGrammarFromPlugins(
  config: PluginGrammarConfig,
): GeneratedGrammar {
  const pluginErrors: string[] = [];
  const orderedPlugins = orderPlugins(config.plugins, pluginErrors);

  const merged = mergePlugins(orderedPlugins, config, pluginErrors);

  const astTypes = rulesToAstTypes(merged.rules);

  const result = generateGrammar({
    grammarName: config.grammarName,
    astTypes,
    tokens: merged.tokens,
    macros: merged.macros,
    precedence: merged.precedence,
    skipWhitespace: merged.skipWhitespace,
    validation: config.validation,
  });

  return {
    grammar: result.grammar,
    imports: result.imports,
    errors: [...pluginErrors, ...result.errors],
  };
}
