import {
  GrammarGeneratorConfig,
  GrammarPlugin,
  GeneratedGrammar,
  PluginGrammarConfig,
  TokenDefinition,
} from "./types.js";

export function generateGrammar(
  config: GrammarGeneratorConfig,
): GeneratedGrammar {
  const tokens = config.tokens || [];
  const errors = validateConfig(config);
  const imports: string[] = [];

  // Build tokens section
  const tokensSection = generateTokensSection(tokens);

  // Build rules section
  const rulesSection = generateRulesSection(config);

  // Build top rule
  const topRule = `@top ${config.grammarName} { ${getStartRule(config)} }`;

  // Build skip section
  const skipSection =
    config.skipWhitespace !== false
      ? `@skip { whitespace | ${getCommentToken(tokens)} }`
      : "";

  // Build precedence section if needed
  const precedenceSection = generatePrecedenceSection(config);

  // Build macros section
  const macrosSection = generateMacrosSection(config.macros);

  const grammar = `/**
 * Generated by @fossiq/lezer-grammar-generator
 * Generated from AST type definitions
 */
${topRule}

${rulesSection}

@tokens {
${tokensSection}
${precedenceSection}}

${skipSection}

${macrosSection}
`;

  return {
    grammar,
    imports,
    errors,
  };
}

export function generateGrammarFromPlugins(
  config: PluginGrammarConfig,
): GeneratedGrammar {
  const pluginErrors: string[] = [];
  const orderedPlugins = orderPlugins(config.plugins, pluginErrors);

  const merged = mergePlugins(orderedPlugins, config, pluginErrors);

  const astTypes = rulesToAstTypes(merged.rules);

  const result = generateGrammar({
    grammarName: config.grammarName,
    astTypes,
    tokens: merged.tokens,
    macros: merged.macros,
    precedence: merged.precedence,
    skipWhitespace: merged.skipWhitespace,
    validation: config.validation,
  });

  return {
    grammar: result.grammar,
    imports: result.imports,
    errors: [...pluginErrors, ...result.errors],
  };
}

function generateMacrosSection(macros?: { [name: string]: string }): string {
  if (!macros) return "";
  return Object.entries(macros)
    .map(([name, body]) => `${name} { ${body} }`)
    .join("\n");
}

function mergePlugins(
  plugins: GrammarPlugin[],
  config: PluginGrammarConfig,
  errors: string[],
): {
  tokens: TokenDefinition[];
  rules: Map<string, string>;
  macros: { [name: string]: string } | undefined;
  precedence: string[] | undefined;
  skipWhitespace: boolean | undefined;
} {
  const tokens: TokenDefinition[] = [];
  const tokenNames = new Set<string>();
  const rules = new Map<string, string>();
  const macros = new Map<string, string>();

  let skipWhitespace: boolean | undefined = config.skipWhitespace;

  for (const plugin of plugins) {
    if (plugin.skipWhitespace !== undefined) {
      if (skipWhitespace === undefined) {
        skipWhitespace = plugin.skipWhitespace;
      } else if (skipWhitespace !== plugin.skipWhitespace) {
        errors.push(
          `Conflicting skipWhitespace across plugins (found both ${String(
            skipWhitespace,
          )} and ${String(plugin.skipWhitespace)}).`,
        );
      }
    }

    for (const token of plugin.tokens ?? []) {
      if (tokenNames.has(token.name)) {
        errors.push(`Duplicate token name '${token.name}' across plugins.`);
        continue;
      }
      tokenNames.add(token.name);
      tokens.push(token);
    }

    for (const [name, rule] of Object.entries(plugin.rules ?? {})) {
      if (rules.has(name)) {
        errors.push(`Duplicate rule name '${name}' across plugins.`);
        continue;
      }
      rules.set(name, rule);
    }

    for (const [name, body] of Object.entries(plugin.macros ?? {})) {
      if (macros.has(name)) {
        const existing = macros.get(name);
        if (existing !== body) {
          errors.push(`Duplicate macro name '${name}' across plugins.`);
        }
        continue;
      }
      macros.set(name, body);
    }
  }

  const precedence =
    config.precedence ??
    mergePrecedence(plugins.map((plugin) => plugin.precedence ?? []));

  return {
    tokens,
    rules,
    macros: macros.size > 0 ? Object.fromEntries(macros) : undefined,
    precedence,
    skipWhitespace,
  };
}

function mergePrecedence(precedenceGroups: string[][]): string[] | undefined {
  const merged: string[] = [];
  const seen = new Set<string>();

  for (const group of precedenceGroups) {
    for (const token of group) {
      if (seen.has(token)) continue;
      seen.add(token);
      merged.push(token);
    }
  }

  return merged.length > 0 ? merged : undefined;
}

function rulesToAstTypes(rules: Map<string, string>) {
  const astTypes: GrammarGeneratorConfig["astTypes"] = {};
  for (const [name, grammarFields] of rules) {
    astTypes[name] = {
      grammarName: name,
      grammarFields,
      isRule: true,
    };
  }
  return astTypes;
}

function orderPlugins(
  plugins: GrammarPlugin[],
  errors: string[],
): GrammarPlugin[] {
  const byName = new Map<string, GrammarPlugin>();

  for (const plugin of plugins) {
    if (!plugin.name || typeof plugin.name !== "string") {
      errors.push("All plugins must have a non-empty `name`.");
      continue;
    }
    if (byName.has(plugin.name)) {
      errors.push(`Duplicate plugin name '${plugin.name}'.`);
      continue;
    }
    byName.set(plugin.name, plugin);
  }

  const ordered: GrammarPlugin[] = [];
  const visiting = new Set<string>();
  const visited = new Set<string>();

  const visit = (name: string) => {
    if (visited.has(name)) return;
    if (visiting.has(name)) {
      errors.push(`Cyclic plugin dependency detected at '${name}'.`);
      return;
    }
    const plugin = byName.get(name);
    if (!plugin) return;

    visiting.add(name);
    for (const dep of plugin.dependsOn ?? []) {
      if (!byName.has(dep)) {
        errors.push(`Plugin '${name}' depends on missing plugin '${dep}'.`);
        continue;
      }
      visit(dep);
    }
    visiting.delete(name);
    visited.add(name);
    ordered.push(plugin);
  };

  for (const plugin of plugins) {
    if (plugin.name && byName.has(plugin.name)) {
      visit(plugin.name);
    }
  }

  return ordered;
}

function generateTokensSection(tokens: TokenDefinition[]): string {
  const tokenLines: string[] = [];
  const overridden = new Set(tokens.map((t) => t.name));

  const addDefault = (name: string, def: string) => {
    if (!overridden.has(name)) {
      tokenLines.push(`  ${name} { ${def} }`);
    }
  };

  tokenLines.push("  // Delimiters");
  addDefault("Pipe", '"|"');
  addDefault("OpenParen", '"("');
  addDefault("CloseParen", '")"');
  addDefault("OpenBracket", '"["');
  addDefault("CloseBracket", '"]"');
  addDefault("Comma", '","');
  addDefault("Semicolon", '";"');
  addDefault("Equals", '"="');
  tokenLines.push("");

  tokenLines.push("  // Math operators");
  addDefault("Plus", '"+"');
  addDefault("Minus", '"-"');
  addDefault("Star", '"*"');
  addDefault("Slash", '"/"');
  addDefault("Percent", '"%"');
  tokenLines.push("");

  tokenLines.push("  // Comparison operators");
  addDefault("ComparisonOp", '"==" | "!=" | ">=" | "<=" | ">" | "<"');
  tokenLines.push("");

  tokenLines.push("  // Basic tokens");
  addDefault("Identifier", "$[a-zA-Z_] $[a-zA-Z0-9_]*");
  addDefault("Number", '@digit+ ("." @digit+)?');

  if (!overridden.has("String")) {
    tokenLines.push("  String {");
    tokenLines.push("    // Standard double quoted");
    tokenLines.push('    """ (!["\\\n] | "\\" _)* """ |');
    tokenLines.push("    // Standard single quoted");
    tokenLines.push('    "\'" (![\'\\\n] | "\\" _)* "\'"');
    tokenLines.push("  }");
  }
  tokenLines.push("");

  tokenLines.push("  // Comments");
  addDefault("LineComment", '"//" ![\n]*');
  addDefault("whitespace", "$[ \t\n\r]+");

  // Add custom tokens
  if (tokens.length > 0) {
    tokenLines.push("");
    tokenLines.push("  // Custom tokens");
    tokens.forEach((token) => {
      if (token.specialized) {
        tokenLines.push(
          `  ${token.name} { @specialize[@name=${token.name}]<${
            token.specialized.base
          }, ${JSON.stringify(token.specialized.term)}> }`,
        );
      } else {
        tokenLines.push(`  ${token.name} { ${token.pattern} }`);
      }
    });
  }

  return tokenLines.join("\n");
}

function generateRulesSection(config: GrammarGeneratorConfig): string {
  const rules: string[] = [];

  for (const def of Object.values(config.astTypes)) {
    if (def.isRule) {
      rules.push(`${def.grammarName} { ${def.grammarFields} }`);
    }
  }

  return rules.join("\n\n");
}

function getStartRule(config: GrammarGeneratorConfig): string {
  // Try to find a rule with a common start type
  const startRules = [
    "statement",
    "document",
    config.grammarName.toLowerCase(),
  ];

  for (const ruleName of startRules) {
    const rule = Object.values(config.astTypes).find(
      (def) => def.grammarName.toLowerCase() === ruleName,
    );
    if (rule && rule.isRule) {
      return rule.grammarName;
    }
  }

  // Fallback to first rule
  const firstRule = Object.values(config.astTypes).find((def) => def.isRule);
  return firstRule ? firstRule.grammarName : "statement";
}

function getCommentToken(tokens: TokenDefinition[]): string {
  const commentToken = tokens.find(
    (t) =>
      t.name === "LineComment" ||
      t.name === "BlockComment" ||
      t.name === "comment",
  );
  return commentToken ? commentToken.name : "LineComment";
}

function generatePrecedenceSection(config: GrammarGeneratorConfig): string {
  if (config.precedence && config.precedence.length > 0) {
    return `\n\n  @precedence {\n    ${config.precedence.join(",\n    ")}\n  }`;
  }

  const precedenceRules: { name: string; precedence: number }[] = [];

  for (const def of Object.values(config.astTypes)) {
    if (def.precedence !== undefined) {
      precedenceRules.push({
        name: def.grammarName,
        precedence: def.precedence,
      });
    }
  }

  if (precedenceRules.length === 0) {
    return "";
  }

  // Group by precedence level
  const byLevel: { [level: number]: string[] } = {};
  precedenceRules.forEach((rule) => {
    if (!byLevel[rule.precedence]) {
      byLevel[rule.precedence] = [];
    }
    byLevel[rule.precedence].push(rule.name);
  });

  const levels = Object.keys(byLevel)
    .map(Number)
    .sort((a, b) => a - b);
  const precedenceLines = levels.map((level) => {
    return `    ${byLevel[level].join(", ")},`;
  });

  return `\n\n  @precedence {\n${precedenceLines.join("\n")}\n  }`;
}

const defaultTokenNames = [
  // Delimiters
  "Pipe",
  "OpenParen",
  "CloseParen",
  "OpenBracket",
  "CloseBracket",
  "Comma",
  "Semicolon",
  "Equals",
  // Math operators
  "Plus",
  "Minus",
  "Star",
  "Slash",
  "Percent",
  // Comparison operators
  "ComparisonOp",
  // Basic tokens
  "Identifier",
  "Number",
  "String",
  // Comments
  "LineComment",
  "whitespace",
] as const;

function validateConfig(config: GrammarGeneratorConfig): string[] {
  const errors: string[] = [];
  const validationMode = config.validation?.mode ?? "basic";
  const allowUnknown = new Set(config.validation?.allowUnknown ?? []);

  if (!config.grammarName || typeof config.grammarName !== "string") {
    errors.push("`grammarName` is required.");
  } else if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(config.grammarName)) {
    errors.push(
      "`grammarName` must be a valid identifier (letters, digits, underscore; cannot start with a digit).",
    );
  }

  if (!config.astTypes || typeof config.astTypes !== "object") {
    errors.push("`astTypes` is required.");
    return errors;
  }

  const astTypeDefs = Object.values(config.astTypes);
  if (astTypeDefs.length === 0) {
    errors.push("`astTypes` must include at least one type definition.");
  }

  const ruleNameCounts = new Map<string, number>();
  let hasRule = false;

  for (const def of astTypeDefs) {
    if (!def.grammarName || typeof def.grammarName !== "string") {
      errors.push("All `astTypes` entries must include `grammarName`.");
      continue;
    }
    if (!def.grammarFields || typeof def.grammarFields !== "string") {
      errors.push(
        `Rule '${def.grammarName}': \`grammarFields\` must be a non-empty string.`,
      );
    } else if (def.grammarFields.trim().length === 0) {
      errors.push(
        `Rule '${def.grammarName}': \`grammarFields\` must be a non-empty string.`,
      );
    } else if (validationMode !== "off") {
      validatePassthrough(
        `Rule '${def.grammarName}': grammarFields`,
        def.grammarFields,
        errors,
      );
    }

    ruleNameCounts.set(
      def.grammarName,
      (ruleNameCounts.get(def.grammarName) || 0) + 1,
    );
    if (def.isRule) hasRule = true;
  }

  for (const [name, count] of ruleNameCounts) {
    if (count > 1) {
      errors.push(`Duplicate rule name '${name}' in \`astTypes\`.`);
    }
  }

  if (!hasRule) {
    errors.push(
      "No rules found: at least one `astTypes` entry must have `isRule: true`.",
    );
  }

  const tokens = config.tokens || [];
  const tokenNameCounts = new Map<string, number>();
  for (const token of tokens) {
    tokenNameCounts.set(token.name, (tokenNameCounts.get(token.name) || 0) + 1);

    if (!token.name || typeof token.name !== "string") {
      errors.push("All `tokens` entries must include `name`.");
      continue;
    }
    if (token.specialized) {
      if (
        !token.specialized.base ||
        typeof token.specialized.base !== "string" ||
        !token.specialized.term ||
        typeof token.specialized.term !== "string"
      ) {
        errors.push(
          `Token '${token.name}': \`specialized\` must include non-empty \`base\` and \`term\`.`,
        );
      }
    } else {
      if (!token.pattern || typeof token.pattern !== "string") {
        errors.push(
          `Token '${token.name}': \`pattern\` must be a non-empty string.`,
        );
      } else if (token.pattern.trim().length === 0) {
        errors.push(
          `Token '${token.name}': \`pattern\` must be a non-empty string.`,
        );
      } else if (validationMode !== "off") {
        validateTokenPattern(
          `Token '${token.name}': pattern`,
          token.pattern,
          errors,
        );
      }
    }
  }

  for (const [name, count] of tokenNameCounts) {
    if (count > 1) {
      errors.push(`Duplicate token name '${name}' in \`tokens\`.`);
    }
  }

  const availableTokens = new Set<string>([
    ...defaultTokenNames,
    ...tokens.map((t) => t.name),
  ]);

  for (const token of tokens) {
    if (
      token.specialized?.base &&
      !availableTokens.has(token.specialized.base)
    ) {
      errors.push(
        `Token '${token.name}': specialized base '${token.specialized.base}' is not a known token.`,
      );
    }
  }

  if (config.precedence) {
    for (const tokenName of config.precedence) {
      if (!availableTokens.has(tokenName)) {
        errors.push(`\`precedence\` references unknown token '${tokenName}'.`);
      }
    }
  }

  if (validationMode !== "off") {
    const macroNames = new Set<string>();
    for (const macroKey of Object.keys(config.macros ?? {})) {
      const baseName = macroKey.split("<", 1)[0]?.trim();
      if (baseName) macroNames.add(baseName);
    }

    for (const def of astTypeDefs) {
      if (!def.grammarName || typeof def.grammarName !== "string") continue;
      if (!def.grammarFields || typeof def.grammarFields !== "string") continue;
      validateMacroInvocations(
        `Rule '${def.grammarName}': grammarFields`,
        def.grammarFields,
        macroNames,
        errors,
      );
    }

    if (validationMode === "strict") {
      const ruleNames = new Set(
        astTypeDefs.map((d) => d.grammarName).filter(Boolean) as string[],
      );
      const known = new Set<string>([
        ...ruleNames,
        ...availableTokens,
        ...macroNames,
      ]);

      for (const def of astTypeDefs) {
        if (!def.grammarName || typeof def.grammarName !== "string") continue;
        if (!def.grammarFields || typeof def.grammarFields !== "string")
          continue;

        const refs = extractBareIdentifiers(def.grammarFields);
        for (const ref of refs) {
          if (ref === "_") continue;
          if (allowUnknown.has(ref)) continue;
          if (!known.has(ref)) {
            errors.push(
              `Rule '${def.grammarName}': grammarFields references unknown identifier '${ref}'.`,
            );
          }
        }
      }
    }
  }

  return errors;
}

function validatePassthrough(label: string, input: string, errors: string[]) {
  const problems = findBalanceProblems(input);
  for (const p of problems) errors.push(`${label}: ${p}`);

  const tokenBalanceProblems = findDelimiterTokenBalanceProblems(input);
  for (const p of tokenBalanceProblems) errors.push(`${label}: ${p}`);

  if (/\|\s*\|/.test(input)) {
    errors.push(`${label}: contains empty alternative ('||').`);
  }
}

function validateTokenPattern(label: string, input: string, errors: string[]) {
  // Token patterns frequently contain quoted strings (and sometimes single-quoted
  // fragments) that we don't try to fully parse here. Keep checks limited to
  // delimiter-token balance and obvious empty alternatives.
  const tokenBalanceProblems = findDelimiterTokenBalanceProblems(input);
  for (const p of tokenBalanceProblems) errors.push(`${label}: ${p}`);

  if (/\|\s*\|/.test(input)) {
    errors.push(`${label}: contains empty alternative ('||').`);
  }
}

function validateMacroInvocations(
  label: string,
  input: string,
  macroNames: Set<string>,
  errors: string[],
) {
  const invocations = extractMacroInvocations(input);
  for (const name of invocations) {
    if (!macroNames.has(name)) {
      errors.push(
        `${label}: uses macro '${name}<...>' but no such macro is defined in config.macros.`,
      );
    }
  }
}

function extractMacroInvocations(input: string): Set<string> {
  const names = new Set<string>();
  const s = input;

  let i = 0;
  let inSingle = false;
  let inDouble = false;
  let escaped = false;

  while (i < s.length) {
    const ch = s[i]!;

    if (inSingle) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === "'") inSingle = false;
      i++;
      continue;
    }

    if (inDouble) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inDouble = false;
      i++;
      continue;
    }

    if (ch === "'") {
      inSingle = true;
      i++;
      continue;
    }
    if (ch === '"') {
      inDouble = true;
      i++;
      continue;
    }

    if (isIdentStart(ch)) {
      const start = i;
      i++;
      while (i < s.length && isIdentPart(s[i]!)) i++;
      const name = s.slice(start, i);
      if (s[i] === "<") names.add(name);
      continue;
    }

    i++;
  }

  return names;
}

function extractBareIdentifiers(input: string): Set<string> {
  const names = new Set<string>();
  const s = input;

  let i = 0;
  let inSingle = false;
  let inDouble = false;
  let escaped = false;

  while (i < s.length) {
    const ch = s[i]!;

    if (inSingle) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === "'") inSingle = false;
      i++;
      continue;
    }
    if (inDouble) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inDouble = false;
      i++;
      continue;
    }

    if (ch === "'") {
      inSingle = true;
      i++;
      continue;
    }
    if (ch === '"') {
      inDouble = true;
      i++;
      continue;
    }

    // Skip Lezer directives like @digit/@specialize and pattern constructs like $[...]
    if (ch === "@" || ch === "$") {
      i++;
      continue;
    }

    if (isIdentStart(ch)) {
      const start = i;
      i++;
      while (i < s.length && isIdentPart(s[i]!)) i++;
      const name = s.slice(start, i);
      names.add(name);
      continue;
    }

    i++;
  }

  return names;
}

function findBalanceProblems(input: string): string[] {
  const problems: string[] = [];
  const stack: string[] = [];

  let inSingle = false;
  let inDouble = false;
  let escaped = false;

  const openToClose: Record<string, string> = { "(": ")", "[": "]", "{": "}" };
  const closeToOpen: Record<string, string> = { ")": "(", "]": "[", "}": "{" };

  for (let i = 0; i < input.length; i++) {
    const ch = input[i]!;

    if (inSingle) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === "'") inSingle = false;
      continue;
    }

    if (inDouble) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inDouble = false;
      continue;
    }

    if (ch === "'") {
      inSingle = true;
      continue;
    }
    if (ch === '"') {
      inDouble = true;
      continue;
    }

    if (openToClose[ch]) {
      stack.push(ch);
      continue;
    }

    if (closeToOpen[ch]) {
      const expectedOpen = closeToOpen[ch]!;
      const actualOpen = stack.pop();
      if (actualOpen !== expectedOpen) {
        problems.push(`unbalanced delimiter near '${ch}'.`);
        break;
      }
    }
  }

  if (inSingle) problems.push("unterminated single-quoted string.");
  if (inDouble) problems.push("unterminated double-quoted string.");
  if (stack.length > 0)
    problems.push("unbalanced delimiters (missing closing bracket/paren).");

  return problems;
}

function findDelimiterTokenBalanceProblems(input: string): string[] {
  const problems: string[] = [];
  const counts = countIdentifiers(input);

  const parenDelta =
    (counts.get("OpenParen") || 0) - (counts.get("CloseParen") || 0);
  if (parenDelta !== 0) {
    problems.push("unbalanced paren tokens (OpenParen/CloseParen).");
  }

  const bracketDelta =
    (counts.get("OpenBracket") || 0) - (counts.get("CloseBracket") || 0);
  if (bracketDelta !== 0) {
    problems.push("unbalanced bracket tokens (OpenBracket/CloseBracket).");
  }

  return problems;
}

function countIdentifiers(input: string): Map<string, number> {
  const counts = new Map<string, number>();
  const s = input;

  let i = 0;
  let inSingle = false;
  let inDouble = false;
  let escaped = false;

  while (i < s.length) {
    const ch = s[i]!;

    if (inSingle) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === "'") inSingle = false;
      i++;
      continue;
    }
    if (inDouble) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inDouble = false;
      i++;
      continue;
    }

    if (ch === "'") {
      inSingle = true;
      i++;
      continue;
    }
    if (ch === '"') {
      inDouble = true;
      i++;
      continue;
    }

    if (ch === "@" || ch === "$") {
      i++;
      continue;
    }

    if (isIdentStart(ch)) {
      const start = i;
      i++;
      while (i < s.length && isIdentPart(s[i]!)) i++;
      const name = s.slice(start, i);
      counts.set(name, (counts.get(name) || 0) + 1);
      continue;
    }

    i++;
  }

  return counts;
}

function isIdentStart(ch: string): boolean {
  return /[A-Za-z_]/.test(ch);
}

function isIdentPart(ch: string): boolean {
  return /[A-Za-z0-9_]/.test(ch);
}
