import {
  GrammarGeneratorConfig,
  GeneratedGrammar,
  TokenDefinition,
} from "./types.js";

export function generateGrammar(
  config: GrammarGeneratorConfig
): GeneratedGrammar {
  const tokens = config.tokens || [];
  const errors: string[] = [];
  const imports: string[] = [];

  // Build tokens section
  const tokensSection = generateTokensSection(tokens);

  // Build rules section
  const rulesSection = generateRulesSection(config);

  // Build top rule
  const topRule = `@top ${config.grammarName} { ${getStartRule(config)} }`;

  // Build skip section
  const skipSection =
    config.skipWhitespace !== false
      ? `@skip { whitespace | ${getCommentToken(tokens)} }`
      : "";

  // Build precedence section if needed
  const precedenceSection = generatePrecedenceSection(config);

  // Build macros section
  const macrosSection = generateMacrosSection(config.macros);

  const grammar = `/**
 * Generated by @fossiq/lezer-grammar-generator
 * Generated from AST type definitions
 */
${topRule}

${rulesSection}

@tokens {
${tokensSection}
${precedenceSection}}

${skipSection}

${macrosSection}
`;

  return {
    grammar,
    imports,
    errors,
  };
}

function generateMacrosSection(macros?: { [name: string]: string }): string {
  if (!macros) return "";
  return Object.entries(macros)
    .map(([name, body]) => `${name} { ${body} }`)
    .join("\n");
}

function generateTokensSection(tokens: TokenDefinition[]): string {
  const tokenLines: string[] = [];
  const overridden = new Set(tokens.map((t) => t.name));

  const addDefault = (name: string, def: string) => {
    if (!overridden.has(name)) {
      tokenLines.push(`  ${name} { ${def} }`);
    }
  };

  tokenLines.push("  // Delimiters");
  addDefault("Pipe", '"|"');
  addDefault("OpenParen", '"("');
  addDefault("CloseParen", '")"');
  addDefault("OpenBracket", '"["');
  addDefault("CloseBracket", '"]"');
  addDefault("Comma", '","');
  addDefault("Semicolon", '";"');
  addDefault("Equals", '"="');
  tokenLines.push("");

  tokenLines.push("  // Math operators");
  addDefault("Plus", '"+"');
  addDefault("Minus", '"-"');
  addDefault("Star", '"*"');
  addDefault("Slash", '"/"');
  addDefault("Percent", '"%"');
  tokenLines.push("");

  tokenLines.push("  // Comparison operators");
  addDefault("ComparisonOp", '"==" | "!=" | ">=" | "<=" | ">" | "<"');
  tokenLines.push("");

  tokenLines.push("  // Basic tokens");
  addDefault("Identifier", "$[a-zA-Z_] $[a-zA-Z0-9_]*");
  addDefault("Number", '@digit+ ("." @digit+)?');

  if (!overridden.has("String")) {
    tokenLines.push("  String {");
    tokenLines.push("    // Standard double quoted");
    tokenLines.push('    """ (!["\\\n] | "\\" _)* """ |');
    tokenLines.push("    // Standard single quoted");
    tokenLines.push('    "\'" (![\'\\\n] | "\\" _)* "\'"');
    tokenLines.push("  }");
  }
  tokenLines.push("");

  tokenLines.push("  // Comments");
  addDefault("LineComment", '"//" ![\n]*');
  addDefault("whitespace", "$[ \t\n\r]+");

  // Add custom tokens
  if (tokens.length > 0) {
    tokenLines.push("");
    tokenLines.push("  // Custom tokens");
    tokens.forEach((token) => {
      if (token.specialized) {
        tokenLines.push(
          `  ${token.name} { @specialize[@name={${token.specialized.term}}]<${token.specialized.base}, ${token.specialized.term}> }`
        );
      } else {
        tokenLines.push(`  ${token.name} { ${token.pattern} }`);
      }
    });
  }

  return tokenLines.join("\n");
}

function generateRulesSection(config: GrammarGeneratorConfig): string {
  const rules: string[] = [];

  for (const def of Object.values(config.astTypes)) {
    if (def.isRule) {
      rules.push(`${def.grammarName} { ${def.grammarFields} }`);
    }
  }

  return rules.join("\n\n");
}

function getStartRule(config: GrammarGeneratorConfig): string {
  // Try to find a rule with a common start type
  const startRules = [
    "statement",
    "document",
    config.grammarName.toLowerCase(),
  ];

  for (const ruleName of startRules) {
    const rule = Object.values(config.astTypes).find(
      (def) => def.grammarName.toLowerCase() === ruleName
    );
    if (rule && rule.isRule) {
      return rule.grammarName;
    }
  }

  // Fallback to first rule
  const firstRule = Object.values(config.astTypes).find((def) => def.isRule);
  return firstRule ? firstRule.grammarName : "statement";
}

function getCommentToken(tokens: TokenDefinition[]): string {
  const commentToken = tokens.find(
    (t) =>
      t.name === "LineComment" ||
      t.name === "BlockComment" ||
      t.name === "comment"
  );
  return commentToken ? commentToken.name : "LineComment";
}

function generatePrecedenceSection(config: GrammarGeneratorConfig): string {
  if (config.precedence && config.precedence.length > 0) {
    return `\n\n  @precedence {\n    ${config.precedence.join(",\n    ")}\n  }`;
  }

  const precedenceRules: { name: string; precedence: number }[] = [];

  for (const def of Object.values(config.astTypes)) {
    if (def.precedence !== undefined) {
      precedenceRules.push({
        name: def.grammarName,
        precedence: def.precedence,
      });
    }
  }

  if (precedenceRules.length === 0) {
    return "";
  }

  // Group by precedence level
  const byLevel: { [level: number]: string[] } = {};
  precedenceRules.forEach((rule) => {
    if (!byLevel[rule.precedence]) {
      byLevel[rule.precedence] = [];
    }
    byLevel[rule.precedence].push(rule.name);
  });

  const levels = Object.keys(byLevel)
    .map(Number)
    .sort((a, b) => a - b);
  const precedenceLines = levels.map((level) => {
    return `    ${byLevel[level].join(", ")},`;
  });

  return `\n\n  @precedence {\n${precedenceLines.join("\n")}\n  }`;
}
