// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,where:10, not:12, contains:16, "!contains":18, startswith:20, endswith:22, has:24, "!has":26, in:28, "!in":30, and:36, or:38, project:40}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&fOYQPOOO_QPO'#CxQOQPOOOgQPO'#CqOxQPO,59dOOQO'#Cy'#CyOOQO,59],59]O!QQPO'#CyO!cQPO'#CyOOQO-E6o-E6oOOQO'#DR'#DRO!hQPO'#C}OOQO'#C}'#C}OOQO'#C|'#C|O#iQPO'#C{O#}QPO'#CzO!QQPO'#C}O!QQPO'#C|OOQO,59e,59eO$`QQO'#DVO$nQPO'#DUOOQO'#DP'#DPO$yQPO,59jO%UQPO,59gO!QQPO'#CrO%jQPO,59fO!QQPO'#CsO%{QPO,59iOOQO,59h,59hO!QQPO,59qO!cQPO'#CtO&QQPO,59pOOQO'#DQ'#DQOOQO1G/U1G/UOOQO-E6p-E6pOOQO,59^,59^OOQO-E6q-E6qOOQO,59_,59_OOQO1G/T1G/TOOQO1G/]1G/]OOQO,59`,59`OOQO-E6r-E6r",
  stateData: "&]~OkOSPOS~ORPO~OSROilX~ORTOTVO`TOaTOdWO~OSROila~ORZOUaO`YOaYOv`O~ORcO~OVeOWeOXeOYeOZeO[eO]eO^eO_eOSqXbqXcqXiqXwqX{qX~ObhOSoXcoXioXwoX{oX~OcjOSnXinXwnX{nX~OzmOSyXiyX{yX~O{nOSxXixX~ORpO`YOaYO~ObhOSoacoaioawoa{oa~OcjOSnainawna{na~OwvO~O{nOSxaixa~O",
  goto: "$UzPPPPPPPPPPPPPPPPPPPPP{!R!X!_PPP!e!h!k!t!|#Y#b#j#m#pPP#{$OQSPRXSQg^RrgQi_RtiQodRyoRQORURQbVQk`RwmU_V`mRujW^V`jmQlaRsh]]V`ahjm][V`ahjmRfZRqf[[V`ahjmRpfRbWQdWRxn",
  nodeNames: "⚠ LineComment Query Identifier Pipe where not ComparisonOp contains !contains startswith endswith has !has in !in Number String and or project",
  maxTerm: 43,
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "&i~RbXY!ZYZ!Z]^!Zpq!Zqr!lrs!wxy$kyz$p|}$u!P!Q$z!Q![%i!^!_%q!_!`%y!`!a%q!c!}&R#R#S&R#T#o&R#p#q&d~!`Sk~XY!ZYZ!Z]^!Zpq!ZP!oP!_!`!rP!wOVP~!zWOY!wZr!wrs#ds#O!w#O#P#i#P;'S!w;'S;=`$e<%lO!w~#iOa~~#lRO;'S!w;'S;=`#u;=`O!w~#xXOY!wZr!wrs#ds#O!w#O#P#i#P;'S!w;'S;=`$e;=`<%l!w<%lO!w~$hP;=`<%l!w~$pOv~~$uOw~~$zO{~~$}P!P!Q%Q~%VSP~OY%QZ;'S%Q;'S;=`%c<%lO%Q~%fP;=`<%l%Q~%nP`~!Q![%iP%vPVP!_!`!rR&OPzQ!_!`!r~&WSR~!Q![&R!c!}&R#R#S&R#T#o&R~&iOS~",
  tokenizers: [0, 1],
  topRules: {"Query":[0,2]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
