// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Query = 2,
  Identifier = 3,
  Pipe = 4,
  ComparisonOp = 5,
  Number = 6,
  String = 7
