// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Query = 2,
  Identifier = 3,
  Pipe = 4,
  where = 5,
  not = 6,
  ComparisonOp = 7,
  contains = 8,
  startswith = 10,
  endswith = 11,
  has = 12,
  _in = 14,
  Number = 16,
  String = 17,
  and = 18,
  or = 19
