module.exports = grammar({
  name: 'kql',

  rules: {
    source_file: ($) => repeat($._statement),
    _statement: ($) => choice($.query_statement),
    query_statement: ($) => seq($.table_name, repeat($.pipe_expression)),
    pipe_expression: ($) => seq("|", $.operator),
    operator: ($) => choice($.where_clause, $.project_clause, $.extend_clause, $.take_clause, $.limit_clause, $.sort_clause, $.order_clause, $.distinct_clause, $.count_clause, $.top_clause, $.search_clause),
    table_name: ($) => $.identifier,
    where_clause: ($) => prec.left(seq("where", $.expression)),
    project_clause: ($) => seq("project", $.column_list),
    extend_clause: ($) => seq("extend", $.column_list),
    take_clause: ($) => seq("take", $.number_literal),
    limit_clause: ($) => seq("limit", $.number_literal),
    top_clause: ($) => seq("top", $.number_literal, optional(seq("by", $.identifier, optional(choice("asc", "desc"))))),
    search_clause: ($) => seq("search", optional(seq("in", "(", $.column_list, ")")), $.string_literal),
    sort_clause: ($) => seq(choice("sort", "order"), optional("by"), $.sort_expression_list),
    order_clause: ($) => seq("order", "by", $.sort_expression_list),
    sort_expression_list: ($) => seq($.sort_expression, repeat(seq(",", $.sort_expression))),
    sort_expression: ($) => seq($.identifier, optional(choice("asc", "desc"))),
    distinct_clause: ($) => seq("distinct", optional($.column_list)),
    count_clause: ($) => "count",
    column_list: ($) => seq($.column_expression, repeat(seq(",", $.column_expression))),
    column_expression: ($) => choice($.identifier, $.column_assignment),
    column_assignment: ($) => seq($.identifier, "=", $.expression),
    expression: ($) => choice($.binary_expression, $.comparison_expression, $.arithmetic_expression, $.string_expression, $.in_expression, $.between_expression, $.parenthesized_expression, $.literal, $.identifier),
    binary_expression: ($) => prec.left(1, seq($.expression, choice("and", "or"), $.expression)),
    comparison_expression: ($) => prec.left(2, seq($.identifier, choice("==", "!=", ">", "<", ">=", "<="), $.literal)),
    arithmetic_expression: ($) => choice(prec.left(4, seq($.expression, choice("*", "/", "%"), $.expression)), prec.left(3, seq($.expression, choice("+", "-"), $.expression))),
    parenthesized_expression: ($) => seq("(", $.expression, ")"),
    string_expression: ($) => prec.left(2, seq($.identifier, choice("contains", "startswith", "endswith", "matches", "has"), $.string_literal)),
    in_expression: ($) => prec.left(2, seq($.identifier, "in", "(", $.literal_list, ")")),
    between_expression: ($) => prec.left(2, seq($.identifier, "between", "(", $.literal, "..", $.literal, ")")),
    literal_list: ($) => seq($.literal, repeat(seq(",", $.literal))),
    literal: ($) => choice($.string_literal, $.number_literal, $.boolean_literal, $.null_literal),
    string_literal: ($) => choice(seq("\"", /[^"]*/, "\""), seq("'", /[^']*/, "'")),
    number_literal: ($) => /\d+(\.\d+)?/,
    boolean_literal: ($) => choice("true", "false"),
    null_literal: ($) => "null",
    identifier: ($) => /[a-zA-Z_][a-zA-Z0-9_]*/,
  }
});
