name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write
  pull-requests: write

jobs:
  lint:
    name: Lint Source
    uses: ./.github/workflows/lint.yml

  build-linux:
    name: Build Linux x64
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      runs-on: ubuntu-24.04
      platform: linux-x64

  build-darwin-arm64:
    name: Build macOS ARM64
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      runs-on: macos-15
      platform: darwin-arm64

  build-darwin-x64:
    name: Build macOS x64
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      runs-on: macos-15-intel
      platform: darwin-x64

  build-win32-x64:
    name: Build Windows x64
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      runs-on: windows-2025
      platform: win32-x64

  test:
    name: Test Suite
    needs:
      - build-linux
      - build-darwin-arm64
      - build-darwin-x64
      - build-win32-x64
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish Packages & UI
    if: github.event_name != 'pull_request'
    needs:
      - test
      - build-linux
      - build-darwin-arm64
      - build-darwin-x64
      - build-win32-x64
    uses: ./.github/workflows/publish.yml
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
