name: Publish

on:
    workflow_call:
        secrets:
            npm-token:
                required: true
            github-token:
                required: true
            deploy-key:
                required: false

jobs:
    publish:
        name: Publish Packages
        runs-on: ubuntu-latest
        environment: release

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: built-packages
                  path: packages

            - name: Setup tooling
              uses: ./.github/actions/setup

            - name: Publish packages via Changesets
              run: bun run release
              env:
                  NPM_TOKEN: ${{ secrets.npm-token }}
                  GITHUB_TOKEN: ${{ secrets.github-token }}

            - name: Deploy UI to GitHub Pages
              if: secrets.deploy-key != ''
              run: bun ./.github/scripts/trigger-ui-deploy.ts
              env:
                  DEPLOY_KEY_GITHUB_IO: ${{ secrets.deploy-key }}
                  GITHUB_SHA: ${{ github.sha }}
                  GITHUB_WORKSPACE: ${{ github.workspace }}
