name: Publish

on:
    workflow_call:
        secrets:
            npm-token:
                required: true
            github-token:
                required: true

jobs:
    publish:
        name: Validate & Publish Packages
        runs-on: ubuntu-24.04
        environment: release

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Download linux-x64 artifacts
              uses: actions/download-artifact@v4
              with:
                  name: built-packages-linux-x64
                  path: temp-linux-x64

            - name: Setup Bun tooling
              uses: ./.github/actions/setup-bun

            - name: Merge build artifacts
              run: bun ./.github/scripts/merge-artifacts.ts

            - name: Publish packages via Changesets
              run: bun run release
              env:
                  NPM_TOKEN: ${{ secrets.npm-token }}
                  GITHUB_TOKEN: ${{ secrets.github-token }}
