name: Test

on:
    workflow_call:

jobs:
    test:
        name: Run Test Suite
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun tooling
              uses: ./.github/actions/setup-bun

            - name: Run Turbo build target
              run: bun x turbo run build --cache-dir=node_modules/.cache/turbo

            - name: Run Turbo test target
              run: bun x turbo run test --cache-dir=node_modules/.cache/turbo
